export declare type CassetteMember<ElementType, MetadataType> = ElementType | Cassette<ElementType, MetadataType>;
export declare type Cassette<ElementType, MetadataType> = [Array<CassetteMember<ElementType, MetadataType>>, Array<CassetteMember<ElementType, MetadataType>>, MetadataType];
export declare function isPlayedCassette<ElementType, MetadataType>(cassette: PlayedCassette<ElementType, MetadataType> | Cassette<ElementType, MetadataType>): cassette is PlayedCassette<ElementType, MetadataType>;
export declare function memberIsCassette<ElementType, MetadataType>(member: CassetteMember<ElementType, MetadataType>): member is Cassette<ElementType, MetadataType>;
export declare function cassetteFromString<MetadataType>(str: string, metadata: MetadataType): Cassette<string, MetadataType>;
export declare function newCassette<ElementType, MetadataType>(arg: Array<CassetteMember<ElementType, MetadataType>>, metadata: MetadataType): Cassette<ElementType, MetadataType>;
export declare function isUnplayed<ElementType, MetadataType>(cassette: Cassette<ElementType, MetadataType>): boolean;
export declare function isFinished<ElementType, MetadataType>([_played, remaining]: Cassette<ElementType, MetadataType>): boolean;
export declare function fastForward<ElementType, MetadataType>(cassette: Cassette<ElementType, MetadataType>): Cassette<ElementType, MetadataType>;
export declare function rewind<ElementType, MetadataType>(cassette: Cassette<ElementType, MetadataType>): Cassette<ElementType, MetadataType>;
export declare function cassetteAsString<MetadataType>(cassette: Cassette<string, MetadataType>): string;
export declare function lastPlayedElement<ElementType, MetadataType>([played, remaining]: Cassette<ElementType, MetadataType>): ElementType | undefined;
export declare type PlayedCassette<ElementType, MetadataType> = [Array<ElementType>, MetadataType];
export declare function playedElements<ElementType, MetadataType>([played, remaining]: Cassette<ElementType, MetadataType>): Array<ElementType | PlayedCassette<ElementType, MetadataType>>;
export declare function nextElement<ElementType, MetadataType>([_played, remaining]: Cassette<ElementType, MetadataType>): ElementType | undefined;
export declare function next<ElementType, MetadataType>(cassette: Cassette<ElementType, MetadataType>): Cassette<ElementType, MetadataType>;
